### ISSUE TITLE
钉钉的webview明显不能满足

### ISSUE THREAD

**Issue by jizhi77** [deboyblog/vue-wechat-title-demo#2]
这个解决方法没有很好地解决问题，测试环境为钉钉内置浏览器。

**Comment by deboyblog** [comment]
iOS10.3.3
钉钉客户端 版本:3.5.1(2474487)
 消息栏 右上角 扫码功能进入演示页面 是正常切换的
华为Meta9 测试确实是有问题的(标题切换延迟)
方便报下你的机型和App版本吗

**Comment by jizhi77** [comment]
测试机型：
1. 华为荣耀8青春版，钉钉3.5.2；
2. Vivo X3t ,钉钉3.5.2
