### ISSUE TITLE
我发现再微信公众平台上不起作用

### ISSUE THREAD

**Issue by ghostJun** [deboyblog/vue-wechat-title-demo#3]
如题，web端浏览没问题，但是微信端浏览title不改变，同时用微信开发者工具测试了你的demo网页，发现titile也没有改变

**Comment by deboyblog** [comment]
开发者工具不用管他 关键是我(`iPhone6s`)和我同事(`一加3T`/`小米5s `)的手机都能正常切换标题 
我也很想修复这个问题😔
但是苦于没有你们手机的机型无法重现出来你们说的`BUG`
贴下使用的代码吧 还有`vuejs`和这个插件的版本号

**Comment by ghostJun** [comment]
谢谢，已经解决了，貌似就是微信开发者工具的锅，部署上线后已经解决了。。。

**Comment by deboyblog** [comment]
ok
