### ISSUE TITLE
chrome 打开站点 一直下载 favicon.ico

### ISSUE THREAD

**Issue by w-mf** [deboyblog/vue-wechat-title-demo#4]
chrome 打开站点 一直下载 favicon.ico

**Comment by deboyblog** [comment]
自己拷贝的代码 还是用的[插件](https://www.npmjs.com/package/vue-wechat-title)?

**Comment by w-mf** [comment]
用的插件
 <  router-view v-wechat-title="$store.state.title" :img-set="favicon"><   /router-view>
....

 import favicon from './img/favicon.ico';
    export default {
        name: 'app',
        data(){
            return {
                favicon:favicon
            }
        },

**Comment by deboyblog** [comment]
我是取路劲 你放到 static 目录下试试
