### ISSUE TITLE
微信开发工具下 title依旧不会变

### ISSUE THREAD

**Issue by xiaosi-ss** [deboyblog/vue-wechat-title-demo#5]
<img width="398" alt="2018-01-20 9 20 48" src="https://user-images.githubusercontent.com/7309546/35183887-f6b9a216-fe27-11e7-891d-86d69e4f5de0.png">
<img width="386" alt="2018-01-20 9 20 57" src="https://user-images.githubusercontent.com/7309546/35183889-f8af034a-fe27-11e7-9b52-527e03d479bd.png">

**Comment by xiaosi-ss** [comment]
感觉好迷茫啊……

**Comment by deboyblog** [comment]
@dan0314 微信开发者工具是不会变的 不是手机微信的环境 不会生效 没办法hack
