### ISSUE TITLE
使用之后HMR一直不断刷新

### ISSUE THREAD

**Issue by usercao** [deboyblog/vue-wechat-title-demo#6]
"vue": "^2.5.2",
"vue-router": "^3.0.1",
"vue-wechat-title": "^2.0.4",
![image](https://user-images.githubusercontent.com/13760476/39687629-eabfc2f0-5201-11e8-99d9-2f1ee95c8db5.png)

使用是history模式的按需加载
```javascript
const HomePage = resolve => require(['@/pages/HomePage'], resolve)
```

![image](https://user-images.githubusercontent.com/13760476/39687799-88dbcd94-5202-11e8-8859-17116e3f074a.png)
上述两种方法测试之后都会不停的刷新页面，title在微信中测试是没问题的

**Comment by deboyblog** [comment]
@usercao 请设置下`img-set`属性 随便指向一个图片文件的相对路径 或者指向一个网络图片 比如百度的logo

**Comment by usercao** [comment]
@deboyblog 我把你2.0的demo拖下来测试后感觉没有什么地方和我不一样，找不到问题出在那里

**Comment by usercao** [comment]
@deboyblog 我是设置什么地方的img-set啊？

**Comment by deboyblog** [comment]
@usercao 方便贴下`main.js`引入的代码吗？
需要远程帮助的话 可以加我QQ : 55631825 我晚点下班有时间可以帮你看看

**Comment by usercao** [comment]
```javascript
import Vue from 'vue'
import App from './App'
import router from './router'
import store from './vuex/store'

import './assets/css/style.css'

Vue.config.productionTip = false
Vue.use(require('vue-wechat-title'))

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  store,
  render: h => h(App)
})
```

**Comment by deboyblog** [comment]
@usercao 
这个图片地址要能访问 你可以随便找一张图片放static目录下 指向它即可
```
<div v-wechat-title="$route.meta.title" img-set="/static/logo.png"></div>
```

**Comment by usercao** [comment]
ok，我试试，我没有设置img-set

**Comment by usercao** [comment]
@deboyblog 按照你描述的添加之后还是不断刷新
```JavaScript
<router-view v-wechat-title="$route.meta.title" img-set="./assets/image/font.png"></router-view>
```

**Comment by usercao** [comment]
会不会是vue-router引起的兼容问题？我将你的demo升级vue-router最新只有到2.8.1版本，我的项目版本是3.0

**Comment by deboyblog** [comment]
@usercao 你设置的图片路径不对 如果是`assets`目录下 的 要用`require`包裹
